application: steam-price-graph
version: live
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

builtins:
- appstats: on
- remote_api: on
- datastore_admin: on

handlers:

# static handlers
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /stylesheets
  static_dir: static/stylesheets
- url: /images
  static_dir: static/images

# the main handler
- url: .*
  script: main.py
